=== Erikhht/tuassembler/trunk/Codigo/TUAssembler/bin/Debug/esquema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="DefinicionFuncion">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ParametroSalida"/>
        <xs:element ref="ParametrosEntrada"/>
      </xs:sequence>
      <xs:attribute name="Nombre" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ParametroSalida">
    <xs:complexType>
      <xs:attribute name="EsMatriz" use="required" type="xs:boolean"/>
      <xs:attribute name="EsVector" use="required" type="xs:boolean"/>
      <xs:attribute name="Tipo" use="required" type="xs:NCName"/>
      <xs:attribute name="TipoDeAcceso" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ParametrosEntrada">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Parametro"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Parametro">
    <xs:complexType>
      <xs:attribute name="CantColumnas" type="xs:integer"/>
      <xs:attribute name="CantFilas" type="xs:integer"/>
      <xs:attribute name="EntradaSalida" type="xs:NCName"/>
      <xs:attribute name="EsMatriz" use="required" type="xs:boolean"/>
      <xs:attribute name="EsVector" use="required" type="xs:boolean"/>
      <xs:attribute name="Longitud" type="xs:integer"/>
      <xs:attribute name="Tipo" use="required" type="xs:NCName"/>
      <xs:attribute name="TipoDeAcceso" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Erikhht/tuassembler/trunk/Codigo/TUAssembler/bin/Debug/archivito.xml
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE DefinicionFuncion []>
<DefinicionFuncion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" Nombre="funcion1" xsi:noNamespaceSchemaLocation="esquema.xsd">
  <ParametroSalida TipoDeAcceso="V" Tipo="UInt16" EsVector="false" EsMatriz="false"/>
  <ParametrosEntrada>
  <!-- Tipos b치sicos por valor-->
    <Parametro TipoDeAcceso="V" Tipo="UInt8" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="V" Tipo="UInt16" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="V" Tipo="UInt32" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="V" Tipo="UInt64" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="V" Tipo="Int8" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="V" Tipo="Int16" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="V" Tipo="Int32" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="V" Tipo="Int64" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="V" Tipo="Float32" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="V" Tipo="Float64" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="V" Tipo="Char" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="V" Tipo="Booleano" EsVector="false" EsMatriz="false"/>
    
    <!-- Tipos b치sicos por referencia, de entrada-->
    <Parametro TipoDeAcceso="R" EntradaSalida="E" Tipo="UInt8" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="E" Tipo="UInt16" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="E" Tipo="UInt32" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="E" Tipo="UInt64" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="E" Tipo="Int8" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="E" Tipo="Int16" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="E" Tipo="Int32" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="E" Tipo="Int64" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="E" Tipo="Float32" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="E" Tipo="Float64" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="E" Tipo="Char" EsVector="false" EsMatriz="false"/>    
    <Parametro TipoDeAcceso="R" EntradaSalida="E" Tipo="Booleano" EsVector="false" EsMatriz="false"/>
    
    <!-- Tipos b치sicos por referencia, de salida-->
    <Parametro TipoDeAcceso="R" EntradaSalida="S" Tipo="UInt8" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="S" Tipo="UInt16" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="S" Tipo="UInt32" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="S" Tipo="UInt64" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="S" Tipo="Int8" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="S" Tipo="Int16" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="S" Tipo="Int32" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="S" Tipo="Int64" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="S" Tipo="Float32" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="S" Tipo="Float64" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="S" Tipo="Char" EsVector="false" EsMatriz="false"/>    
    <Parametro TipoDeAcceso="R" EntradaSalida="S" Tipo="Booleano" EsVector="false" EsMatriz="false"/>
    
    <!-- Tipos b치sicos por referencia, de entrada-salida-->
    <Parametro TipoDeAcceso="R" EntradaSalida="ES" Tipo="UInt8" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="ES" Tipo="UInt16" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="ES" Tipo="UInt32" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="ES" Tipo="UInt64" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="ES" Tipo="Int8" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="ES" Tipo="Int16" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="ES" Tipo="Int32" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="ES" Tipo="Int64" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="ES" Tipo="Float32" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="ES" Tipo="Float64" EsVector="false" EsMatriz="false"/>
    <Parametro TipoDeAcceso="R" EntradaSalida="ES" Tipo="Char" EsVector="false" EsMatriz="false"/>    
    <Parametro TipoDeAcceso="R" EntradaSalida="ES" Tipo="Booleano" EsVector="false" EsMatriz="false"/>
    
    <!-- Vector(long fija), de todos los tipos, de entrada-->
    <Parametro EntradaSalida="E" Tipo="UInt8" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="E" Tipo="UInt16" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="E" Tipo="UInt32" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="E" Tipo="UInt64" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="E" Tipo="Int8" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="E" Tipo="Int16" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="E" Tipo="Int32" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="E" Tipo="Int64" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="E" Tipo="Float32" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="E" Tipo="Float64" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="E" Tipo="Char" EsVector="true" Longitud="5" EsMatriz="false"/>    
    <Parametro EntradaSalida="E" Tipo="Booleano" EsVector="true" Longitud="5" EsMatriz="false"/>
    
    <!-- Vector(long fija), de todos los tipos, de salida-->
    <Parametro EntradaSalida="S" Tipo="UInt8" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="S" Tipo="UInt16" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="S" Tipo="UInt32" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="S" Tipo="UInt64" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="S" Tipo="Int8" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="S" Tipo="Int16" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="S" Tipo="Int32" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="S" Tipo="Int64" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="S" Tipo="Float32" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="S" Tipo="Float64" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="S" Tipo="Char" EsVector="true" Longitud="5" EsMatriz="false"/>    
    <Parametro EntradaSalida="S" Tipo="Booleano" EsVector="true" Longitud="5" EsMatriz="false"/>
    
    <!-- Vector(long fija), de todos los tipos, de entrada-salida-->
    <Parametro EntradaSalida="ES" Tipo="UInt8" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="ES" Tipo="UInt16" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="ES" Tipo="UInt32" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="ES" Tipo="UInt64" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="ES" Tipo="Int8" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="ES" Tipo="Int16" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="ES" Tipo="Int32" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="ES" Tipo="Int64" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="ES" Tipo="Float32" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="ES" Tipo="Float64" EsVector="true" Longitud="5" EsMatriz="false"/>
    <Parametro EntradaSalida="ES" Tipo="Char" EsVector="true" Longitud="5" EsMatriz="false"/>    
    <Parametro EntradaSalida="ES" Tipo="Booleano" EsVector="true" Longitud="5" EsMatriz="false"/>
                                                                                                    
		<!-- Matriz(long fija), de todos los tipos, de entrada-->                                                                                                                                           
		<Parametro EntradaSalida="E" Tipo="UInt8" EsVector="false" CantFilas="3" CantColumnas="5" EsMatriz="true"/>  
		<Parametro EntradaSalida="E" Tipo="UInt16" EsVector="false" CantFilas="3" CantColumnas="5" EsMatriz="true"/>  
		<Parametro EntradaSalida="E" Tipo="UInt32" EsVector="false" CantFilas="3" CantColumnas="5" EsMatriz="true"/>  
		<Parametro EntradaSalida="E" Tipo="UInt64" EsVector="false" CantFilas="3" CantColumnas="5" EsMatriz="true"/>  
		<Parametro EntradaSalida="E" Tipo="Int8" EsVector="false" CantFilas="3" CantColumnas="5" EsMatriz="true"/>  
		<Parametro EntradaSalida="E" Tipo="Int16" EsVector="false" CantFilas="3" CantColumnas="5" EsMatriz="true"/>  
		<Parametro EntradaSalida="E" Tipo="Int32" EsVector="false" CantFilas="3" CantColumnas="5" EsMatriz="true"/>
